import matplotlib.pyplot as plt
import networkx as nx
from meu_grafo_lista_adj import *


def visualizar_grafo(grafo, titulo):
    G = nx.Graph()
    for v in grafo.vertices:
        G.add_node(str(v))
    for a in grafo.arestas.values():
        G.add_edge(str(a.v1.rotulo), str(a.v2.rotulo))

    # Posicionamento utilizando o layout Circular
    pos = nx.circular_layout(G)

    # Definindo o título antes de exibir o gráfico
    plt.title(titulo)
    nx.draw(G, pos, with_labels=True)
    plt.show()

# DFS
g_c_dfs = MeuGrafo()
g_c_dfs.adiciona_vertice("C")
g_c_dfs.adiciona_vertice("J")
g_c_dfs.adiciona_vertice("E")
g_c_dfs.adiciona_vertice("P")
g_c_dfs.adiciona_aresta('a1', 'J', 'C')
g_c_dfs.adiciona_aresta('a4', 'C', 'E')
g_c_dfs.adiciona_aresta('a6', 'E', 'P')

g_c_dfs2 = MeuGrafo()
g_c_dfs2.adiciona_vertice("C")
g_c_dfs2.adiciona_vertice("J")
g_c_dfs2.adiciona_vertice("E")
g_c_dfs2.adiciona_vertice("P")
g_c_dfs2.adiciona_aresta('a1', 'C', 'J')
g_c_dfs2.adiciona_aresta('a2', 'J', 'E')
g_c_dfs2.adiciona_aresta('a6', 'E', 'P')

g_c_dfs3 = MeuGrafo()
g_c_dfs3.adiciona_vertice("C")
g_c_dfs3.adiciona_vertice("J")
g_c_dfs3.adiciona_vertice("E")
g_c_dfs3.adiciona_vertice("P")
g_c_dfs3.adiciona_aresta('a2', 'E', 'J')
g_c_dfs3.adiciona_aresta('a1', 'J', 'C')
g_c_dfs3.adiciona_aresta('a5', 'C', 'P')

g_c_dfs4 = MeuGrafo()
g_c_dfs4.adiciona_vertice("C")
g_c_dfs4.adiciona_vertice("J")
g_c_dfs4.adiciona_vertice("E")
g_c_dfs4.adiciona_vertice("P")
g_c_dfs4.adiciona_aresta('a3', 'P', 'J')
g_c_dfs4.adiciona_aresta('a1', 'J', 'C')
g_c_dfs4.adiciona_aresta('a4', 'C', 'E')

g_p_dfs = MeuGrafo()
g_p_dfs.adiciona_vertice("J")
g_p_dfs.adiciona_vertice("C")
g_p_dfs.adiciona_vertice("E")
g_p_dfs.adiciona_vertice("P")
g_p_dfs.adiciona_vertice("M")
g_p_dfs.adiciona_vertice("T")
g_p_dfs.adiciona_vertice("Z")
g_p_dfs.adiciona_aresta('a1', 'C', 'J')
g_p_dfs.adiciona_aresta('a2', 'C', 'E')
g_p_dfs.adiciona_aresta('a4', 'C', 'P')
g_p_dfs.adiciona_aresta('a6', 'T', 'C')
g_p_dfs.adiciona_aresta('a7', 'C', 'M')
g_p_dfs.adiciona_aresta('a9', 'T', 'Z')

g_p_dfs2 = MeuGrafo()
g_p_dfs2.adiciona_vertice("J")
g_p_dfs2.adiciona_vertice("C")
g_p_dfs2.adiciona_vertice("E")
g_p_dfs2.adiciona_vertice("P")
g_p_dfs2.adiciona_vertice("M")
g_p_dfs2.adiciona_vertice("T")
g_p_dfs2.adiciona_vertice("Z")
g_p_dfs2.adiciona_aresta('a1', 'J', 'C')
g_p_dfs2.adiciona_aresta('a2', 'C', 'E')
g_p_dfs2.adiciona_aresta('a4', 'P', 'C')
g_p_dfs2.adiciona_aresta('a7', 'M', 'C')
g_p_dfs2.adiciona_aresta('a8', 'M', 'T')
g_p_dfs2.adiciona_aresta('a9', 'T', 'Z')

g_p_dfs3 = MeuGrafo()
g_p_dfs3.adiciona_vertice("J")
g_p_dfs3.adiciona_vertice("C")
g_p_dfs3.adiciona_vertice("E")
g_p_dfs3.adiciona_vertice("P")
g_p_dfs3.adiciona_vertice("M")
g_p_dfs3.adiciona_vertice("T")
g_p_dfs3.adiciona_vertice("Z")
g_p_dfs3.adiciona_aresta('a1', 'J', 'C')
g_p_dfs3.adiciona_aresta('a2', 'C', 'E')
g_p_dfs3.adiciona_aresta('a4', 'P', 'C')
g_p_dfs3.adiciona_aresta('a6', 'T', 'C')
g_p_dfs3.adiciona_aresta('a8', 'M', 'T')
g_p_dfs3.adiciona_aresta('a9', 'T', 'Z')

g_p_dfs4 = MeuGrafo()
g_p_dfs4.adiciona_vertice("J")
g_p_dfs4.adiciona_vertice("C")
g_p_dfs4.adiciona_vertice("E")
g_p_dfs4.adiciona_vertice("P")
g_p_dfs4.adiciona_vertice("M")
g_p_dfs4.adiciona_vertice("T")
g_p_dfs4.adiciona_vertice("Z")
g_p_dfs4.adiciona_aresta('a1', 'J', 'C')
g_p_dfs4.adiciona_aresta('a2', 'C', 'E')
g_p_dfs4.adiciona_aresta('a4', 'P', 'C')
g_p_dfs4.adiciona_aresta('a6', 'T', 'C')
g_p_dfs4.adiciona_aresta('a8', 'M', 'T')
g_p_dfs4.adiciona_aresta('a9', 'T', 'Z')


g_c_bfs = MeuGrafo()
g_c_bfs.adiciona_vertice("J")
g_c_bfs.adiciona_vertice("C")
g_c_bfs.adiciona_vertice("E")
g_c_bfs.adiciona_vertice("P")
g_c_bfs.adiciona_aresta('a1', 'J', 'C')
g_c_bfs.adiciona_aresta('a2', 'J', 'E')
g_c_bfs.adiciona_aresta('a3', 'J', 'P')

g_c_bfs2 = MeuGrafo()
g_c_bfs2.adiciona_vertice("J")
g_c_bfs2.adiciona_vertice("C")
g_c_bfs2.adiciona_vertice("E")
g_c_bfs2.adiciona_vertice("P")
g_c_bfs2.adiciona_aresta('a1', 'J', 'C')
g_c_bfs2.adiciona_aresta('a4', 'E', 'C')
g_c_bfs2.adiciona_aresta('a5', 'P', 'C')

g_c_bfs3 = MeuGrafo()
g_c_bfs3.adiciona_vertice("J")
g_c_bfs3.adiciona_vertice("C")
g_c_bfs3.adiciona_vertice("E")
g_c_bfs3.adiciona_vertice("P")
g_c_bfs3.adiciona_aresta('a2', 'J', 'E')
g_c_bfs3.adiciona_aresta('a4', 'E', 'C')
g_c_bfs3.adiciona_aresta('a6', 'P', 'E')

g_c_bfs4 = MeuGrafo()
g_c_bfs4.adiciona_vertice("J")
g_c_bfs4.adiciona_vertice("C")
g_c_bfs4.adiciona_vertice("E")
g_c_bfs4.adiciona_vertice("P")
g_c_bfs4.adiciona_aresta('a3', 'J', 'P')
g_c_bfs4.adiciona_aresta('a5', 'P', 'C')
g_c_bfs4.adiciona_aresta('a6', 'P', 'E')


g_p_bfs = MeuGrafo()
g_p_bfs.adiciona_vertice("J")
g_p_bfs.adiciona_vertice("C")
g_p_bfs.adiciona_vertice("E")
g_p_bfs.adiciona_vertice("P")
g_p_bfs.adiciona_vertice("M")
g_p_bfs.adiciona_vertice("T")
g_p_bfs.adiciona_vertice("Z")
g_p_bfs.adiciona_aresta('a1', 'J', 'C')
g_p_bfs.adiciona_aresta('a2', 'C', 'E')
g_p_bfs.adiciona_aresta('a4', 'P', 'C')
g_p_bfs.adiciona_aresta('a6', 'T', 'C')
g_p_bfs.adiciona_aresta('a8', 'M', 'T')
g_p_bfs.adiciona_aresta('a9', 'T', 'Z')

g_p_bfs2 = MeuGrafo()
g_p_bfs2.adiciona_vertice("J")
g_p_bfs2.adiciona_vertice("C")
g_p_bfs2.adiciona_vertice("E")
g_p_bfs2.adiciona_vertice("P")
g_p_bfs2.adiciona_vertice("M")
g_p_bfs2.adiciona_vertice("T")
g_p_bfs2.adiciona_vertice("Z")
g_p_bfs2.adiciona_aresta('a1', 'J', 'C')
g_p_bfs2.adiciona_aresta('a2', 'C', 'E')
g_p_bfs2.adiciona_aresta('a4', 'P', 'C')
g_p_bfs2.adiciona_aresta('a6', 'T', 'C')
g_p_bfs2.adiciona_aresta('a7', 'M', 'C')
g_p_bfs2.adiciona_aresta('a9', 'T', 'Z')

g_p_bfs3 = MeuGrafo()
g_p_bfs3.adiciona_vertice("J")
g_p_bfs3.adiciona_vertice("C")
g_p_bfs3.adiciona_vertice("E")
g_p_bfs3.adiciona_vertice("P")
g_p_bfs3.adiciona_vertice("M")
g_p_bfs3.adiciona_vertice("T")
g_p_bfs3.adiciona_vertice("Z")
g_p_bfs3.adiciona_aresta('a1', 'J', 'C')
g_p_bfs3.adiciona_aresta('a2', 'C', 'E')
g_p_bfs3.adiciona_aresta('a4', 'P', 'C')
g_p_bfs3.adiciona_aresta('a6', 'T', 'C')
g_p_bfs3.adiciona_aresta('a8', 'M', 'T')
g_p_bfs3.adiciona_aresta('a9', 'T', 'Z')

g_p_bfs4 = MeuGrafo()
g_p_bfs4.adiciona_vertice("J")
g_p_bfs4.adiciona_vertice("C")
g_p_bfs4.adiciona_vertice("E")
g_p_bfs4.adiciona_vertice("P")
g_p_bfs4.adiciona_vertice("M")
g_p_bfs4.adiciona_vertice("T")
g_p_bfs4.adiciona_vertice("Z")
g_p_bfs4.adiciona_aresta('a1', 'J', 'C')
g_p_bfs4.adiciona_aresta('a2', 'C', 'E')
g_p_bfs4.adiciona_aresta('a4', 'P', 'C')
g_p_bfs4.adiciona_aresta('a6', 'T', 'C')
g_p_bfs4.adiciona_aresta('a8', 'M', 'T')
g_p_bfs4.adiciona_aresta('a9', 'T', 'Z')

g_sem_ciclos = MeuGrafo()
g_sem_ciclos.adiciona_vertice("A")
g_sem_ciclos.adiciona_vertice("B")
g_sem_ciclos.adiciona_vertice("C")
g_sem_ciclos.adiciona_vertice("D")
g_sem_ciclos.adiciona_vertice("E")
g_sem_ciclos.adiciona_vertice("F")
g_sem_ciclos.adiciona_vertice("G")
g_sem_ciclos.adiciona_aresta('a1', 'A', 'B')
g_sem_ciclos.adiciona_aresta('a2', 'A', 'C')
g_sem_ciclos.adiciona_aresta('a3', 'B', 'D')
g_sem_ciclos.adiciona_aresta('a4', 'B', 'E')
g_sem_ciclos.adiciona_aresta('a5', 'C', 'F')
g_sem_ciclos.adiciona_aresta('a6', 'C', 'G')

#visualizar_grafo(g_c_dfs, "RAIZ 'J'")
#visualizar_grafo(g_c_dfs2, "RAIZ 'C'")
#visualizar_grafo(g_c_dfs3, "RAIZ 'E'")
#visualizar_grafo(g_c_dfs4, "RAIZ 'P'")
#visualizar_grafo(g_c3, "RAIZ 'Único'")
#visualizar_grafo(g_c2, "RAIZ 'Nina'")
#visualizar_grafo(g_p_dfs, "RAIZ 'T'")
#visualizar_grafo(g_p_dfs2, "RAIZ 'J'")
#visualizar_grafo(g_p_dfs3, "RAIZ 'C'")
#visualizar_grafo(g_p_dfs4, "RAIZ 'E'")


#visualizar_grafo(g_c_bfs, "RAIZ 'J'")
#visualizar_grafo(g_c_bfs2, "RAIZ 'C'")
#visualizar_grafo(g_c_bfs3, "RAIZ 'E'")
#visualizar_grafo(g_c_bfs4, "RAIZ 'P'")
#visualizar_grafo(g_p_bfs, "RAIZ 'T'")
#visualizar_grafo(g_p_bfs2, "RAIZ 'J'")
#visualizar_grafo(g_p_bfs3, "RAIZ 'C'")
#visualizar_grafo(g_sem_ciclos, "Grafo sem ciclo")